# Generated by Django 4.1 on 2023-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_cattle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
