# Generated by Django 4.1 on 2023-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
