# Generated by Django 3.2.5 on 2023-03-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_remove_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
