# Generated by Django 3.2.5 on 2023-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_cattle_pregnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='lost_status',
            field=models.BooleanField(default=False),
        ),
    ]
